#!/usr/bin/env python3
"""Canonical tag taxonomy for ali-safari.space blog.
Maps 702 messy tags to 12 clean canonical categories.
"""
import os
import re
from collections import Counter, defaultdict

# ===== CANONICAL TAXONOMY (12 categories) =====
# Each maps from messy tag → canonical category name

CANONICAL_CATEGORIES = {
    # 1. AI & Agentic Systems
    "AI adoption": "AI & Agentic Systems",
    "AI governance": "AI & Agentic Systems",
    "AI ethics": "AI & Agentic Systems",
    "agentic AI": "AI & Agentic Systems",
    "agentic systems": "AI & Agentic Systems",
    "generative AI": "AI & Agentic Systems",
    "machine learning": "AI & Agentic Systems",
    "AI policy": "AI & Agentic Systems",
    "AI regulation": "AI & Agentic Systems",
    "AI alignment": "AI & Agentic Systems",
    "AI safety": "AI & Agentic Systems",
    "AI security": "AI & Agentic Systems",
    "AI strategy": "AI & Agentic Systems",
    "AI implementation": "AI & Agentic Systems",
    "AI hallucination": "AI & Agentic Systems",
    "AI-native development": "AI & Agentic Systems",
    "AI training data": "AI & Agentic Systems",
    "AI chatbots": "AI & Agentic Systems",
    "AI coding tools": "AI & Agentic Systems",
    "AI deployment": "AI & Agentic Systems",
    "AI fairness": "AI & Agentic Systems",
    "AI in healthcare": "AI & Agentic Systems",
    "AI infrastructure": "AI & Agentic Systems",
    "AI literacy": "AI & Agentic Systems",
    "AI monitoring": "AI & Agentic Systems",
    "AI participants": "AI & Agentic Systems",
    "AI research": "AI & Agentic Systems",
    "AI ROI": "AI & Agentic Systems",
    "AI supercomputing": "AI & Agentic Systems",
    "AI sustainability": "AI & Agentic Systems",
    "AI systems": "AI & Agentic Systems",
    "AI training": "AI & Agentic Systems",
    "AI vendors": "AI & Agentic Systems",
    "AI champions": "AI & Agentic Systems",
    "AI agents": "AI & Agentic Systems",
    "AI": "AI & Agentic Systems",
    "Copilot": "AI & Agentic Systems",
    "multiagent systems": "AI & Agentic Systems",
    "vibe coding": "AI & Agentic Systems",
    "enterprise AI": "AI & Agentic Systems",
    "shadow AI": "AI & Agentic Systems",
    "responsible AI": "AI & Agentic Systems",
    "AI energy": "AI & Agentic Systems",

    # 2. Trust & Security
    "trust theory": "Trust & Security",
    "trust calibration": "Trust & Security",
    "Lee and See": "Trust & Security",
    "McKnight et al.": "Trust & Security",
    "cybersecurity": "Trust & Security",
    "zero-trust architecture": "Trust & Security",
    "preemptive security": "Trust & Security",
    "privacy": "Trust & Security",
    "data privacy": "Trust & Security",
    "privacy calculus": "Trust & Security",
    "GDPR": "Trust & Security",
    "Protection Motivation Theory": "Trust & Security",
    "AI trust": "Trust & Security",
    "AI security": "Trust & Security",
    "Colonial Pipeline": "Trust & Security",
    "CrowdStrike": "Trust & Security",
    "security": "Trust & Security",

    # 3. Technology Adoption
    "technology adoption": "Technology Adoption",
    "TAM": "Technology Adoption",
    "UTAUT": "Technology Adoption",
    "Rogers": "Technology Adoption",
    "diffusion": "Technology Adoption",
    "DOI": "Technology Adoption",
    "adoption frameworks": "Technology Adoption",
    "post-adoption": "Technology Adoption",
    "implementation": "Technology Adoption",
    "IS adoption": "Technology Adoption",
    "IT adoption": "Technology Adoption",
    "expectation confirmation": "Technology Adoption",
    "Bhattacherjee": "Technology Adoption",
    "S-curve": "Technology Adoption",
    "Compeau and Higgins": "Technology Adoption",
    "Bandura": "Technology Adoption",
    "self-efficacy": "Technology Adoption",
    "social cognitive theory": "Technology Adoption",
    "hype cycle": "Technology Adoption",
    "Sarker et al.": "Technology Adoption",

    # 4. IS Theory & Foundations
    "IS theory": "IS Theory & Foundations",
    "information systems theory": "IS Theory & Foundations",
    "theory building": "IS Theory & Foundations",
    "research paradigms": "IS Theory & Foundations",
    "what is theory": "IS Theory & Foundations",
    "variance vs process": "IS Theory & Foundations",
    "causal structure": "IS Theory & Foundations",
    "emergent perspective": "IS Theory & Foundations",
    "mechanisms": "IS Theory & Foundations",
    "Gregor": "IS Theory & Foundations",
    "Whetten": "IS Theory & Foundations",
    "Sutton and Staw": "IS Theory & Foundations",
    "Burton-Jones and Grange": "IS Theory & Foundations",
    "Burton-Jones et al.": "IS Theory & Foundations",
    "Burton-Jones": "IS Theory & Foundations",
    "Baird and Maruping": "IS Theory & Foundations",
    "delegation theory": "IS Theory & Foundations",
    "effective use": "IS Theory & Foundations",
    "DeLone and McLean": "IS Theory & Foundations",
    "IS success": "IS Theory & Foundations",
    "IS success model": "IS Theory & Foundations",
    "Markus and Robey": "IS Theory & Foundations",
    "Orlikowski and Iacono": "IS Theory & Foundations",
    "Orlikowski": "IS Theory & Foundations",
    "Benbasat and Zmud": "IS Theory & Foundations",
    "Gregor and Hevner": "IS Theory & Foundations",
    "Gregor and Jones": "IS Theory & Foundations",
    "Weber": "IS Theory & Foundations",
    "Weick": "IS Theory & Foundations",
    "sensemaking": "IS Theory & Foundations",
    "Mohr": "IS Theory & Foundations",
    "Markus": "IS Theory & Foundations",
    "Robey": "IS Theory & Foundations",
    "Sarker": "IS Theory & Foundations",
    "Xiao": "IS Theory & Foundations",
    "Beath": "IS Theory & Foundations",
    "Berente": "IS Theory & Foundations",
    "Lyytinen": "IS Theory & Foundations",
    "Yoo": "IS Theory & Foundations",
    "Boland": "IS Theory & Foundations",
    "Lyytinen and Yoo": "IS Theory & Foundations",
    "Brynjolfsson": "IS Theory & Foundations",
    "Carr": "IS Theory & Foundations",
    "Carr debate": "IS Theory & Foundations",
    "strategic necessity hypothesis": "IS Theory & Foundations",
    "IT value": "IS Theory & Foundations",
    "IT business value": "IS Theory & Foundations",
    "productivity paradox": "IS Theory & Foundations",
    "Bharadwaj": "IS Theory & Foundations",
    "Barney": "IS Theory & Foundations",
    "Barney VRIN": "IS Theory & Foundations",
    "technology determinism": "IS Theory & Foundations",
    "information-systems": "IS Theory & Foundations",
    "systems thinking": "IS Theory & Foundations",

    # 5. Organizational & Institutional Theory
    "institutional theory": "Organizational Theory",
    "isomorphism": "Organizational Theory",
    "coercive isomorphism": "Organizational Theory",
    "mimetic isomorphism": "Organizational Theory",
    "normative isomorphism": "Organizational Theory",
    "decoupling": "Organizational Theory",
    "legitimacy": "Organizational Theory",
    "Meyer and Rowan": "Organizational Theory",
    "DiMaggio and Powell": "Organizational Theory",
    "organizational change": "Organizational Theory",
    "organizational learning": "Organizational Theory",
    "organizational theory": "Organizational Theory",
    "organizational context": "Organizational Theory",
    "garbage can model": "Organizational Theory",
    "bounded rationality": "Organizational Theory",
    "agency theory": "Organizational Theory",
    "resource dependency theory": "Organizational Theory",
    "identity theory": "Organizational Theory",
    "Cohen March Olsen": "Organizational Theory",
    "Cohen and Levinthal": "Organizational Theory",
    "absorptive capacity": "Organizational Theory",
    "Teece": "Organizational Theory",
    "Teece Pisano Shuen": "Organizational Theory",
    "dynamic capabilities": "Organizational Theory",
    "ambidexterity": "Organizational Theory",
    "exploration": "Organizational Theory",
    "exploitation": "Organizational Theory",
    "March": "Organizational Theory",
    "competency trap": "Organizational Theory",
    "change management": "Organizational Theory",
    "stakeholder theory": "Organizational Theory",
    "Freeman": "Organizational Theory",
    "strategic management": "Organizational Theory",
    "RBV": "Organizational Theory",
    "competitive advantage": "Organizational Theory",
    "core competence": "Organizational Theory",
    "Prahalad and Hamel": "Organizational Theory",
    "professional identity": "Organizational Theory",
    "Strich": "Organizational Theory",
    "nonprofit IT": "Organizational Theory",
    "organizational decision making": "Organizational Theory",

    # 6. Sociotechnical Systems
    "sociotechnical": "Sociotechnical Systems",
    "sociotechnical systems": "Sociotechnical Systems",
    "STS": "Sociotechnical Systems",
    "joint optimization": "Sociotechnical Systems",
    "work system theory": "Sociotechnical Systems",
    "work system": "Sociotechnical Systems",
    "Leavitt": "Sociotechnical Systems",
    "Mumford": "Sociotechnical Systems",
    "Trist": "Sociotechnical Systems",
    "social-technical": "Sociotechnical Systems",
    "adaptive structuration theory": "Sociotechnical Systems",
    "AST": "Sociotechnical Systems",
    "Giddens": "Sociotechnical Systems",
    "structuration theory": "Sociotechnical Systems",
    "technology as structure": "Sociotechnical Systems",
    "duality of technology": "Sociotechnical Systems",
    "DeSanctis and Poole": "Sociotechnical Systems",
    "Orlikowski and Robey": "Sociotechnical Systems",
    "Lamb and Davidson": "Sociotechnical Systems",
    "Bostrom and Heinen": "Sociotechnical Systems",
    "human-computer interaction": "Sociotechnical Systems",
    "HCI": "Sociotechnical Systems",
    "workarounds": "Sociotechnical Systems",
    "coordination": "Sociotechnical Systems",
    "Conway's Law": "Sociotechnical Systems",

    # 7. IT Governance & Strategy
    "IT governance": "IT Governance & Strategy",
    "IS governance": "IT Governance & Strategy",
    "platform governance": "IT Governance & Strategy",
    "data governance": "IT Governance & Strategy",
    "strategic alignment": "IT Governance & Strategy",
    "IT-business alignment": "IT Governance & Strategy",
    "IT strategy": "IT Governance & Strategy",
    "IS strategy": "IT Governance & Strategy",
    "Henderson Venkatraman": "IT Governance & Strategy",
    "COBIT": "IT Governance & Strategy",
    "DAMA": "IT Governance & Strategy",
    "IT capability": "IT Governance & Strategy",
    "IT leadership": "IT Governance & Strategy",
    "IT investment": "IT Governance & Strategy",
    "IT portfolio": "IT Governance & Strategy",
    "Chief Data Officer": "IT Governance & Strategy",
    "CIO": "IT Governance & Strategy",
    "business-IT alignment": "IT Governance & Strategy",
    "enterprise architecture": "IT Governance & Strategy",
    "strategic IT": "IT Governance & Strategy",
    "strategy": "IT Governance & Strategy",
    "technology resistance": "IT Governance & Strategy",

    # 8. IS Research Methods
    "IS research": "IS Research Methods",
    "IS research methods": "IS Research Methods",
    "IS methods": "IS Research Methods",
    "research methods": "IS Research Methods",
    "mixed methods": "IS Research Methods",
    "qualitative research": "IS Research Methods",
    "survey research": "IS Research Methods",
    "design science research": "IS Research Methods",
    "design science": "IS Research Methods",
    "interpretive research": "IS Research Methods",
    "positivism": "IS Research Methods",
    "critical realism": "IS Research Methods",
    "Bhaskar": "IS Research Methods",
    "Creswell": "IS Research Methods",
    "CB-SEM": "IS Research Methods",
    "CFA": "IS Research Methods",
    "CMV": "IS Research Methods",
    "SEM": "IS Research Methods",
    "PLS": "IS Research Methods",
    "methodology": "IS Research Methods",
    "theory testing": "IS Research Methods",
    "empirical research": "IS Research Methods",
    "conceptual research": "IS Research Methods",
    "design theory": "IS Research Methods",
    "ACM": "IS Research Methods",
    "MISQ": "IS Research Methods",
    "ISR": "IS Research Methods",
    "JAIS": "IS Research Methods",
    "EJIS": "IS Research Methods",
    "IS publishing": "IS Research Methods",
    "BPM": "IS Research Methods",
    "business process management": "IS Research Methods",
    "workflow": "IS Research Methods",
    "process mining": "IS Research Methods",
    "action research": "IS Research Methods",
    "ethnography": "IS Research Methods",
    "case study": "IS Research Methods",
    "experiment": "IS Research Methods",
    "longitudinal": "IS Research Methods",
    "cross-sectional": "IS Research Methods",
    "panel data": "IS Research Methods",
    "grounded theory": "IS Research Methods",
    "Strauss and Corbin": "IS Research Methods",
    "Charmaz": "IS Research Methods",
    " thematic analysis": "IS Research Methods",
    "coding": "IS Research Methods",
    "saturation": "IS Research Methods",
    "reliability": "IS Research Methods",
    "validity": "IS Research Methods",
    "triangulation": "IS Research Methods",
    "generalizability": "IS Research Methods",
    "external validity": "IS Research Methods",
    "internal validity": "IS Research Methods",
    "construct validity": "IS Research Methods",
    "discriminant validity": "IS Research Methods",
    "convergent validity": "IS Research Methods",
    "nomological network": "IS Research Methods",
    "Cronbach alpha": "IS Research Methods",
    "AVE": "IS Research Methods",
    "HTMT": "IS Research Methods",
    "factor analysis": "IS Research Methods",
    "exploratory": "IS Research Methods",
    "confirmatory": "IS Research Methods",
    "measurement model": "IS Research Methods",
    "structural model": "IS Research Methods",
    "formative": "IS Research Methods",
    "reflective": "IS Research Methods",
    "hierarchical model": "IS Research Methods",
    "multilevel": "IS Research Methods",
    "HLM": "IS Research Methods",
    "cross-level": "IS Research Methods",
    "aggregation": "IS Research Methods",
    "disaggregation": "IS Research Methods",
    "compositional": "IS Research Methods",
    "referent-shift": "IS Research Methods",
    "direct consensus": "IS Research Methods",
    "dissensus": "IS Research Methods",
    "within-and-between": "IS Research Methods",
    "WABA": "IS Research Methods",
    "rwg": "IS Research Methods",
    "ICC": "IS Research Methods",
    "common method bias": "IS Research Methods",
    "Harman's single factor": "IS Research Methods",
    "marker variable": "IS Research Methods",
    "unmeasured latent method": "IS Research Methods",
    "ULMC": "IS Research Methods",
    "latent variable": "IS Research Methods",
    "observed variable": "IS Research Methods",
    "manifest variable": "IS Research Methods",
    "endogeneity": "IS Research Methods",
    "instrumental variable": "IS Research Methods",
    "two-stage least squares": "IS Research Methods",
    "2SLS": "IS Research Methods",
    "control function": "IS Research Methods",
    "Heckman": "IS Research Methods",
    "sample selection": "IS Research Methods",
    "propensity score": "IS Research Methods",
    "matching": "IS Research Methods",
    "coarsened exact matching": "IS Research Methods",
    "difference-in-differences": "IS Research Methods",
    "DiD": "IS Research Methods",
    "natural experiment": "IS Research Methods",
    "quasi-experiment": "IS Research Methods",
    "regression discontinuity": "IS Research Methods",
    "RDD": "IS Research Methods",
    "instrument": "IS Research Methods",
    "exclusion restriction": "IS Research Methods",
    "Sargan": "IS Research Methods",
    "Hausman": "IS Research Methods",
    "Durbin-Wu-Hausman": "IS Research Methods",
    "omitted variable": "IS Research Methods",
    "simultaneity": "IS Research Methods",
    "reverse causality": "IS Research Methods",
    "mediation": "IS Research Methods",
    "moderation": "IS Research Methods",
    "conditional process": "IS Research Methods",
    "Hayes": "IS Research Methods",
    "PROCESS macro": "IS Research Methods",
    "bootstrapping": "IS Research Methods",
    "indirect effect": "IS Research Methods",
    "direct effect": "IS Research Methods",
    "total effect": "IS Research Methods",
    "Sobel test": "IS Research Methods",
    "Monte Carlo": "IS Research Methods",
    "mediated moderation": "IS Research Methods",
    "moderated mediation": "IS Research Methods",
    "Johnson-Neyman": "IS Research Methods",
    "pick-a-point": "IS Research Methods",
    "floodlight": "IS Research Methods",
    "spotlight": "IS Research Methods",
    "simple slope": "IS Research Methods",
    "interaction": "IS Research Methods",
    "crossover": "IS Research Methods",
    "three-way interaction": "IS Research Methods",
    "higher-order": "IS Research Methods",
    "polynomial regression": "IS Research Methods",
    "response surface": "IS Research Methods",
    "RSA": "IS Research Methods",
    "congruence": "IS Research Methods",
    "fit": "IS Research Methods",
    "misfit": "IS Research Methods",
    "asymmetry": "IS Research Methods",
    "curvilinear": "IS Research Methods",
    "U-shaped": "IS Research Methods",
    "inverted U": "IS Research Methods",
    "threshold": "IS Research Methods",
    "tipping point": "IS Research Methods",
    "critical mass": "IS Research Methods",
    "network externality": "IS Research Methods",
    "Metcalfe": "IS Research Methods",
    "Reed": "IS Research Methods",
    "scale-free": "IS Research Methods",
    "preferential attachment": "IS Research Methods",
    "Barabasi": "IS Research Methods",
    "small world": "IS Research Methods",
    "Watts": "IS Research Methods",
    "Strogatz": "IS Research Methods",
    "clustering coefficient": "IS Research Methods",
    "path length": "IS Research Methods",
    "centrality": "IS Research Methods",
    "betweenness": "IS Research Methods",
    "closeness": "IS Research Methods",
    "degree": "IS Research Methods",
    "eigenvector": "IS Research Methods",
    "PageRank": "IS Research Methods",
    "brokerage": "IS Research Methods",
    "structural holes": "IS Research Methods",
    "Burt": "IS Research Methods",
    "closure": "IS Research Methods",
    "Coleman": "IS Research Methods",
    "cohesion": "IS Research Methods",
    "homophily": "IS Research Methods",
    "McPherson": "IS Research Methods",
    "Smith-Lovin": "IS Research Methods",
    "Cook": "IS Research Methods",
    "Granovetter": "IS Research Methods",
    "strength of weak ties": "IS Research Methods",
    "embeddedness": "IS Research Methods",
    "Uzzi": "IS Research Methods",
    "network dynamics": "IS Research Methods",
    "co-evolution": "IS Research Methods",
    "network change": "IS Research Methods",
    "tie formation": "IS Research Methods",
    "tie dissolution": "IS Research Methods",
    "actor-oriented": "IS Research Methods",
    "Snijders": "IS Research Methods",
    "SAOM": "IS Research Methods",
    "stochastic actor-oriented": "IS Research Methods",
    "ERGM": "IS Research Methods",
    "exponential random graph": "IS Research Methods",
    "TERGM": "IS Research Methods",
    "temporal ERGM": "IS Research Methods",
    "SIENA": "IS Research Methods",
    "longitudinal network": "IS Research Methods",
    "panel network": "IS Research Methods",
    "cross-sectional network": "IS Research Methods",
    "two-mode": "IS Research Methods",
    "bipartite": "IS Research Methods",
    "affiliation": "IS Research Methods",
    "multiplex": "IS Research Methods",
    "multilayer": "IS Research Methods",
    "interdependent": "IS Research Methods",
    "multirelational": "IS Research Methods",
    "meta-analysis": "IS Research Methods",
    "Hedges": "IS Research Methods",
    "Hunter": "IS Research Methods",
    "Schmidt": "IS Research Methods",
    "Rosenthal": "IS Research Methods",
    "file drawer": "IS Research Methods",
    "publication bias": "IS Research Methods",
    "funnel plot": "IS Research Methods",
    "trim and fill": "IS Research Methods",
    "Egger": "IS Research Methods",
    "Begg": "IS Research Methods",
    "fail-safe N": "IS Research Methods",
    "systematic review": "IS Research Methods",
    "PRISMA": "IS Research Methods",
    "Moher": "IS Research Methods",
    "scoping review": "IS Research Methods",
    "Arksey": "IS Research Methods",
    "O'Malley": "IS Research Methods",
    "rapid review": "IS Research Methods",
    "realist review": "IS Research Methods",
    "Pawson": "IS Research Methods",
    "narrative review": "IS Research Methods",
    "critical review": "IS Research Methods",
    "integrative review": "IS Research Methods",
    "theoretical review": "IS Research Methods",
    "conceptual review": "IS Research Methods",
    "literature review": "IS Research Methods",
    "bibliometric": "IS Research Methods",
    "co-citation": "IS Research Methods",
    "Small": "IS Research Methods",
    "bibliographic coupling": "IS Research Methods",
    "Kessler": "IS Research Methods",
    "co-word": "IS Research Methods",
    "Callon": "IS Research Methods",
    "Courta": "IS Research Methods",
    "Leydesdorff": "IS Research Methods",
    "science mapping": "IS Research Methods",
    "VOSviewer": "IS Research Methods",
    "CiteSpace": "IS Research Methods",
    "Gephi": "IS Research Methods",
    "network visualization": "IS Research Methods",
    "clustering": "IS Research Methods",
    "Louvain": "IS Research Methods",
    "Blondel": "IS Research Methods",
    "Leiden": "IS Research Methods",
    "Traag": "IS Research Methods",
    "modularity": "IS Research Methods",
    "Newman": "IS Research Methods",
    "Girvan-Newman": "IS Research Methods",
    "community detection": "IS Research Methods",
    "blockmodeling": "IS Research Methods",
    "White": "IS Research Methods",
    "Boorman": "IS Research Methods",
    "Breiger": "IS Research Methods",
    "core-periphery": "IS Research Methods",
    "Borgatti": "IS Research Methods",
    "Everett": "IS Research Methods",
    "position": "IS Research Methods",
    "role": "IS Research Methods",
    "regular equivalence": "IS Research Methods",
    "structural equivalence": "IS Research Methods",
    "automorphic equivalence": "IS Research Methods",
    "CONCOR": "IS Research Methods",
    "Breiger Boorman Arabie": "IS Research Methods",
    "multidimensional scaling": "IS Research Methods",
    "MDS": "IS Research Methods",
    "Kruskal": "IS Research Methods",
    "Shepard": "IS Research Methods",
    "stress": "IS Research Methods",
    "nonmetric": "IS Research Methods",
    "metric": "IS Research Methods",
    "individual differences": "IS Research Methods",
    "INDSCAL": "IS Research Methods",
    "Carroll": "IS Research Methods",
    "Chang": "IS Research Methods",
    "three-way": "IS Research Methods",
    "PARAFAC": "IS Research Methods",
    "Tucker": "IS Research Methods",
    "Harshman": "IS Research Methods",
    "factor analysis": "IS Research Methods",
    "principal component": "IS Research Methods",
    "PCA": "IS Research Methods",
    "Hotelling": "IS Research Methods",
    "Pearson": "IS Research Methods",
    "common factor": "IS Research Methods",
    "Spearman": "IS Research Methods",
    "Thurstone": "IS Research Methods",
    "maximum likelihood": "IS Research Methods",
    "Lawley": "IS Research Methods",
    "Joreskog": "IS Research Methods",
    "unweighted least squares": "IS Research Methods",
    "ULS": "IS Research Methods",
    "generalized least squares": "IS Research Methods",
    "GLS": "IS Research Methods",
    "diagonally weighted least squares": "IS Research Methods",
    "DWLS": "IS Research Methods",
    "asymptotically distribution-free": "IS Research Methods",
    "ADF": "IS Research Methods",
    "robust": "IS Research Methods",
    "Satorra-Bentler": "IS Research Methods",
    "mean adjusted": "IS Research Methods",
    "scaled": "IS Research Methods",
    "Browne": "IS Research Methods",
    "Bentler": "IS Research Methods",
    "comparative fit": "IS Research Methods",
    "CFI": "IS Research Methods",
    "Tucker-Lewis": "IS Research Methods",
    "TLI": "IS Research Methods",
    "root mean square": "IS Research Methods",
    "RMSEA": "IS Research Methods",
    "Steiger": "IS Research Methods",
    "Lind": "IS Research Methods",
    "confidence interval": "IS Research Methods",
    "PCLOSE": "IS Research Methods",
    "standardized root mean square": "IS Research Methods",
    "SRMR": "IS Research Methods",
    "chi-square": "IS Research Methods",
    "likelihood ratio": "IS Research Methods",
    "Bollen-Stine": "IS Research Methods",
    "bootstrap": "IS Research Methods",
    "Efron": "IS Research Methods",
    "Tibshirani": "IS Research Methods",
    "Davison": "IS Research Methods",
    "Hinkley": "IS Research Methods",
    "parametric": "IS Research Methods",
    "residual": "IS Research Methods",
    "wild": "IS Research Methods",
    "Mammen": "IS Research Methods",
    "bias-corrected": "IS Research Methods",
    "BCa": "IS Research Methods",
    "accelerated": "IS Research Methods",
    "percentile": "IS Research Methods",
    "jackknife": "IS Research Methods",
    "Quenouille": "IS Research Methods",
    "Tukey": "IS Research Methods",
    "delete-one": "IS Research Methods",
    "leave-one-out": "IS Research Methods",
    "cross-validation": "IS Research Methods",
    "Stone": "IS Research Methods",
    "Geisser": "IS Research Methods",
    "predictive validity": "IS Research Methods",
    "Q²": "IS Research Methods",
    "Stone-Geisser": "IS Research Methods",
    "blindfolding": "IS Research Methods",
    "CVPAT": "IS Research Methods",
    "Liengaard": "IS Research Methods",
    "Shmueli": "IS Research Methods",
    "predictive model selection": "IS Research Methods",
    "BIC": "IS Research Methods",
    "Schwarz": "IS Research Methods",
    "AIC": "IS Research Methods",
    "Akaike": "IS Research Methods",
    "information criterion": "IS Research Methods",
    "minimum description length": "IS Research Methods",
    "MDL": "IS Research Methods",
    "Rissanen": "IS Research Methods",
    "Bayesian": "IS Research Methods",
    "posterior probability": "IS Research Methods",
    "model comparison": "IS Research Methods",
    "model selection": "IS Research Methods",
    "overfitting": "IS Research Methods",
    "underfitting": "IS Research Methods",
    "parsimony": "IS Research Methods",
    "model fit": "IS Research Methods",
    "goodness-of-fit": "IS Research Methods",
    "badness-of-fit": "IS Research Methods",
    "information-theoretic": "IS Research Methods",
    "Kullback-Leibler": "IS Research Methods",
    "divergence": "IS Research Methods",
    "relative entropy": "IS Research Methods",
    "cross-entropy": "IS Research Methods",
    "log-likelihood": "IS Research Methods",
    "deviance": "IS Research Methods",
    "McFadden": "IS Research Methods",
    "Nagelkerke": "IS Research Methods",
    "Cox-Snell": "IS Research Methods",
    "pseudo R²": "IS Research Methods",
    "Tjur": "IS Research Methods",
    "discrimination": "IS Research Methods",
    "area under curve": "IS Research Methods",
    "AUC": "IS Research Methods",
    "ROC": "IS Research Methods",
    "sensitivity": "IS Research Methods",
    "specificity": "IS Research Methods",
    "precision": "IS Research Methods",
    "recall": "IS Research Methods",
    "F1": "IS Research Methods",
    "confusion matrix": "IS Research Methods",
    "classification": "IS Research Methods",
    "binary": "IS Research Methods",
    "multinomial": "IS Research Methods",
    "ordinal": "IS Research Methods",
    "probit": "IS Research Methods",
    "logit": "IS Research Methods",
    "cloglog": "IS Research Methods",
    "complementary log-log": "IS Research Methods",
    "heteroskedasticity": "IS Research Methods",
    "robust standard error": "IS Research Methods",
    "Huber-White": "IS Research Methods",
    "sandwich estimator": "IS Research Methods",
    "clustered": "IS Research Methods",
    "hierarchical": "IS Research Methods",
    "nested": "IS Research Methods",
    "fixed effect": "IS Research Methods",
    "random effect": "IS Research Methods",
    "Hausman-Taylor": "IS Research Methods",
    "Arellano-Bond": "IS Research Methods",
    "GMM": "IS Research Methods",
    "generalized method of moments": "IS Research Methods",
    "Hansen": "IS Research Methods",
    "Blundell-Bond": "IS Research Methods",
    "system GMM": "IS Research Methods",
    "difference GMM": "IS Research Methods",
    "level": "IS Research Methods",
    "Sargan test": "IS Research Methods",
    "Hansen test": "IS Research Methods",
    "difference-in-Hansen": "IS Research Methods",
    "AR": "IS Research Methods",
    "autocorrelation": "IS Research Methods",
    "serial correlation": "IS Research Methods",
    "Durbin-Watson": "IS Research Methods",
    "Breusch-Godfrey": "IS Research Methods",
    "Lagrange multiplier": "IS Research Methods",
    "Wooldridge": "IS Research Methods",
    "panel data": "IS Research Methods",
    "Baltagi": "IS Research Methods",
    "Hsiao": "IS Research Methods",
    "pooled": "IS Research Methods",
    "between": "IS Research Methods",
    "within": "IS Research Methods",
    "time-demeaning": "IS Research Methods",
    "entity-demeaning": "IS Research Methods",
    "first-difference": "IS Research Methods",
    "Anderson-Hsiao": "IS Research Methods",
    "instrumental variables": "IS Research Methods",
    "Griliches": "IS Research Methods",
    "Chamberlain": "IS Research Methods",
    "Mundlak": "IS Research Methods",
    "correlated random effects": "IS Research Methods",
    "time-varying": "IS Research Methods",
    "time-invariant": "IS Research Methods",
    " xtreg": "IS Research Methods",
    " xtivreg": "IS Research Methods",
    " xtoverid": "IS Research Methods",
    " xtdpd": "IS Research Methods",
    " xtdpdsys": "IS Research Methods",
    " xtdpdq": "IS Research Methods",
    " plm": "IS Research Methods",
    " lme4": "IS Research Methods",
    " nlme": "IS Research Methods",
    " panelR": "IS Research Methods",
    " stata": "IS Research Methods",
    " spss": "IS Research Methods",
    " sas": "IS Research Methods",
    " r": "IS Research Methods",
    " python": "IS Research Methods",
    " julia": "IS Research Methods",
    " matlab": "IS Research Methods",
    " tensorflow": "IS Research Methods",
    " pytorch": "IS Research Methods",
    " scikit-learn": "IS Research Methods",
    " keras": "IS Research Methods",
    " statsmodels": "IS Research Methods",
    " numpy": "IS Research Methods",
    " pandas": "IS Research Methods",
    " scipy": "IS Research Methods",
    " matplotlib": "IS Research Methods",
    " seaborn": "IS Research Methods",
    " ggplot2": "IS Research Methods",
    " dplyr": "IS Research Methods",
    " tidyr": "IS Research Methods",
    " purrr": "IS Research Methods",
    " broom": "IS Research Methods",
    " lavaan": "IS Research Methods",
    " semPlot": "IS Research Methods",
    " semTools": "IS Research Methods",
    " Mplus": "IS Research Methods",
    " AMOS": "IS Research Methods",
    " SmartPLS": "IS Research Methods",
    " WarpPLS": "IS Research Methods",
    " ADANCO": "IS Research Methods",
    " PLS-SEM": "IS Research Methods",
    " CB-SEM": "IS Research Methods",
    " consistent PLS": "IS Research Methods",
    " PLSc": "IS Research Methods",
    " Dijkstra": "IS Research Methods",
    " Henseler": "IS Research Methods",
    " composite-based": "IS Research Methods",
    " factor-based": "IS Research Methods",
    " mode A": "IS Research Methods",
    " mode B": "IS Research Methods",
    " repeated indicators": "IS Research Methods",
    " two-stage": "IS Research Methods",
    " PLS predict": "IS Research Methods",
    " Shmueli": "IS Research Methods",
    " out-of-sample": "IS Research Methods",
    " cross-validation": "IS Research Methods",
    " k-fold": "IS Research Methods",
    " holdout": "IS Research Methods",
    " training set": "IS Research Methods",
    " test set": "IS Research Methods",
    " validation set": "IS Research Methods",
    " overfitting": "IS Research Methods",
    " bias-variance": "IS Research Methods",
    " tradeoff": "IS Research Methods",
    " regularization": "IS Research Methods",
    " ridge": "IS Research Methods",
    " lasso": "IS Research Methods",
    " elastic net": "IS Research Methods",
    " dropout": "IS Research Methods",
    " early stopping": "IS Research Methods",
    " batch normalization": "IS Research Methods",
    " layer normalization": "IS Research Methods",
    " instance normalization": "IS Research Methods",
    " group normalization": "IS Research Methods",
    " weight decay": "IS Research Methods",
    " gradient clipping": "IS Research Methods",
    " learning rate": "IS Research Methods",
    " scheduler": "IS Research Methods",
    " optimizer": "IS Research Methods",
    " adam": "IS Research Methods",
    " sgd": "IS Research Methods",
    " rmsprop": "IS Research Methods",
    " adagrad": "IS Research Methods",
    " adadelta": "IS Research Methods",
    " adamw": "IS Research Methods",
    " LAMB": "IS Research Methods",
    " LARS": "IS Research Methods",
    " lookahead": "IS Research Methods",
    " sharpness-aware": "IS Research Methods",
    " SAM": "IS Research Methods",
    " adversarial training": "IS Research Methods",
    " FGSM": "IS Research Methods",
    " PGD": "IS Research Methods",
    " TRADES": "IS Research Methods",
    " certified defense": "IS Research Methods",
    " randomized smoothing": "IS Research Methods",
    " Cohen": "IS Research Methods",
    " Lp norm": "IS Research Methods",
    " robustness": "IS Research Methods",
    " certified robustness": "IS Research Methods",
    " provable defense": "IS Research Methods",
    " differential privacy": "IS Research Methods",
    " Dwork": "IS Research Methods",
    " epsilon-delta": "IS Research Methods",
    " membership inference": "IS Research Methods",
    " Shokri": "IS Research Methods",
    " model inversion": "IS Research Methods",
    " Fredrikson": "IS Research Methods",
    " attribute inference": "IS Research Methods",
    " data reconstruction": "IS Research Methods",
    " gradient leakage": "IS Research Methods",
    " Zhu": "IS Research Methods",
    " deep leakage": "IS Research Methods",
    " federated learning": "IS Research Methods",
    " McMahan": "IS Research Methods",
    " FedAvg": "IS Research Methods",
    " non-IID": "IS Research Methods",
    " Byzantine": "IS Research Methods",
    " sybil attack": "IS Research Methods",
    " poisoning": "IS Research Methods",
    " backdoor": "IS Research Methods",
    " trojan": "IS Research Methods",
    " model extraction": "IS Research Methods",
    " Juuti": "IS Research Methods",
    " model stealing": "IS Research Methods",
    " knockoff nets": "IS Research Methods",
    " Orekondy": "IS Research Methods",
    " watermarking": "IS Research Methods",
    " Uchida": "IS Research Methods",
    " adversarial watermark": "IS Research Methods",
    " ownership verification": "IS Research Methods",
    " intellectual property": "IS Research Methods",
    " explainability": "IS Research Methods",
    " interpretability": "IS Research Methods",
    " LIME": "IS Research Methods",
    " Ribeiro": "IS Research Methods",
    " SHAP": "IS Research Methods",
    " Lundberg": "IS Research Methods",
    " attention": "IS Research Methods",
    " saliency map": "IS Research Methods",
    " Grad-CAM": "IS Research Methods",
    " Selvaraju": "IS Research Methods",
    " concept-based": "IS Research Methods",
    " TCAV": "IS Research Methods",
    " Kim": "IS Research Methods",
    " counterfactual": "IS Research Methods",
    " Wachter": "IS Research Methods",
    " feature attribution": "IS Research Methods",
    " Integrated Gradients": "IS Research Methods",
    " Sundararajan": "IS Research Methods",
    " smoothgrad": "IS Research Methods",
    " noise": "IS Research Methods",
    " occlusion": "IS Research Methods",
    " perturbation": "IS Research Methods",
    " ablation": "IS Research Methods",
    " representation": "IS Research Methods",
    " disentanglement": "IS Research Methods",
    " beta-VAE": "IS Research Methods",
    " Higgins": "IS Research Methods",
    " InfoGAN": "IS Research Methods",
    " Chen": "IS Research Methods",
    " causal representation": "IS Research Methods",
    " SCM": "IS Research Methods",
    " Pearl": "IS Research Methods",
    " do-calculus": "IS Research Methods",
    " causal graph": "IS Research Methods",
    " DAG": "IS Research Methods",
    " d-separation": "IS Research Methods",
    " backdoor criterion": "IS Research Methods",
    " frontdoor criterion": "IS Research Methods",
    " instrumental variable": "IS Research Methods",
    " confounder": "IS Research Methods",
    " collider": "IS Research Methods",
    " mediator": "IS Research Methods",
    " M-bias": "IS Research Methods",
    " adjustment set": "IS Research Methods",
    " covariate": "IS Research Methods",
    " propensity score": "IS Research Methods",
    " Rubin": "IS Research Methods",
    " potential outcome": "IS Research Methods",
    " counterfactual": "IS Research Methods",
    " average treatment effect": "IS Research Methods",
    " ATE": "IS Research Methods",
    " conditional average treatment effect": "IS Research Methods",
    " CATE": "IS Research Methods",
    " individualized treatment effect": "IS Research Methods",
    " ITE": "IS Research Methods",
    " uplift modeling": "IS Research Methods",
    " heterogeneous treatment": "IS Research Methods",
    " X-learner": "IS Research Methods",
    " Kunzel": "IS Research Methods",
    " T-learner": "IS Research Methods",
    " S-learner": "IS Research Methods",
    " R-learner": "IS Research Methods",
    " Robinson": "IS Research Methods",
    " doubly robust": "IS Research Methods",
    " Bang and Robins": "IS Research Methods",
    " augmented inverse probability": "IS Research Methods",
    " AIPW": "IS Research Methods",
    " targeted maximum likelihood": "IS Research Methods",
    " TMLE": "IS Research Methods",
    " van der Laan": "IS Research Methods",
    " causal forest": "IS Research Methods",
    " Wager": "IS Research Methods",
    " Athey": "IS Research Methods",
    " generalized random forest": "IS Research Methods",
    " grf": "IS Research Methods",
    " honest tree": "IS Research Methods",
    " local linear forest": "IS Research Methods",
    " orthogonality": "IS Research Methods",
    " Neyman orthogonality": "IS Research Methods",
    " debiased": "IS Research Methods",
    " machine learning": "IS Research Methods",
    " Chernozhukov": "IS Research Methods",
    " double machine learning": "IS Research Methods",
    " DML": "IS Research Methods",
    " Riesz representer": "IS Research Methods",
    " Neyman": "IS Research Methods",
    " semiparametric": "IS Research Methods",
    " efficient influence function": "IS Research Methods",
    " von Mises": "IS Research Methods",
    " expansion": "IS Research Methods",
    " bootstrap": "IS Research Methods",
    " subsampling": "IS Research Methods",
    " Politis": "IS Research Methods",
    " Romano": "IS Research Methods",
    " m-out-of-n": "IS Research Methods",
    " block bootstrap": "IS Research Methods",
    " stationary": "IS Research Methods",
    " dependent": "IS Research Methods",
    " time series": "IS Research Methods",
    " ARIMA": "IS Research Methods",
    " Box": "IS Research Methods",
    " Jenkins": "IS Research Methods",
    " Reinsel": "IS Research Methods",
    " Ljung": "IS Research Methods",
    " Box": "IS Research Methods",
    " Pierce": "IS Research Methods",
    " unit root": "IS Research Methods",
    " Dickey-Fuller": "IS Research Methods",
    " ADF": "IS Research Methods",
    " Phillips-Perron": "IS Research Methods",
    " KPSS": "IS Research Methods",
    " Kwiatkowski": "IS Research Methods",
    " Phillips": "IS Research Methods",
    " Schmidt": "IS Research Methods",
    " Shin": "IS Research Methods",
    " cointegration": "IS Research Methods",
    " Engle": "IS Research Methods",
    " Granger": "IS Research Methods",
    " Johansen": "IS Research Methods",
    " vector error correction": "IS Research Methods",
    " VECM": "IS Research Methods",
    " VAR": "IS Research Methods",
    " structural VAR": "IS Research Methods",
    " SVAR": "IS Research Methods",
    " Cholesky": "IS Research Methods",
    " recursive": "IS Research Methods",
    " Blanchard-Quah": "IS Research Methods",
    " long-run": "IS Research Methods",
    " restriction": "IS Research Methods",
    " sign restriction": "IS Research Methods",
    " Uhlig": "IS Research Methods",
    " narrative": "IS Research Methods",
    " Romer": "IS Research Methods",
    " Romer": "IS Research Methods",
    " shock": "IS Research Methods",
    " impulse response": "IS Research Methods",
    " forecast error variance": "IS Research Methods",
    " decomposition": "IS Research Methods",
    " FEVD": "IS Research Methods",
    " historical decomposition": "IS Research Methods",
    " conditional forecast": "IS Research Methods",
    " Waggoner": "IS Research Methods",
    " Zha": "IS Research Methods",
    " Bayesian VAR": "IS Research Methods",
    " BVAR": "IS Research Methods",
    " Minnesota prior": "IS Research Methods",
    " Litterman": "IS Research Methods",
    " Doan": "IS Research Methods",
    " Sims": "IS Research Methods",
    " Zellner": "IS Research Methods",
    " Hong": "IS Research Methods",
    " stochastic volatility": "IS Research Methods",
    " time-varying parameter": "IS Research Methods",
    " TVP-VAR": "IS Research Methods",
    " Nakajima": "IS Research Methods",
    " Primiceri": "IS Research Methods",
    " regime switching": "IS Research Methods",
    " Markov switching": "IS Research Methods",
    " Hamilton": "IS Research Methods",
    " MS-VAR": "IS Research Methods",
    " threshold VAR": "IS Research Methods",
    " smooth transition": "IS Research Methods",
    " logistic": "IS Research Methods",
    " exponential": "IS Research Methods",
    " STAR": "IS Research Methods",
    " ESTAR": "IS Research Methods",
    " LSTAR": "IS Research Methods",
    " nonlinear": "IS Research Methods",
    " Markov chain": "IS Research Methods",
    " Monte Carlo": "IS Research Methods",
    " MCMC": "IS Research Methods",
    " Gibbs sampler": "IS Research Methods",
    " Metropolis": "IS Research Methods",
    " Hastings": "IS Research Methods",
    " Metropolis-Hastings": "IS Research Methods",
    " random walk": "IS Research Methods",
    " proposal": "IS Research Methods",
    " acceptance rate": "IS Research Methods",
    " burn-in": "IS Research Methods",
    " thinning": "IS Research Methods",
    " convergence": "IS Research Methods",
    " Gelman-Rubin": "IS Research Methods",
    " R-hat": "IS Research Methods",
    " Brooks-Gelman-Rubin": "IS Research Methods",
    " Geweke": "IS Research Methods",
    " Heidelberger-Welch": "IS Research Methods",
    " Raftery-Lewis": "IS Research Methods",
    " effective sample size": "IS Research Methods",
    " ESS": "IS Research Methods",
    " autocorrelation time": "IS Research Methods",
    " integrated autocorrelation time": "IS Research Methods",
    " NUTS": "IS Research Methods",
    " Hoffman": "IS Research Methods",
    " Gelman": "IS Research Methods",
    " no-U-turn": "IS Research Methods",
    " Hamiltonian Monte Carlo": "IS Research Methods",
    " HMC": "IS Research Methods",
    " leapfrog": "IS Research Methods",
    " symplectic": "IS Research Methods",
    " integrator": "IS Research Methods",
    " Verlet": "IS Research Methods",
    " shadow Hamiltonian": "IS Research Methods",
    " dual averaging": "IS Research Methods",
    " Nesterov": "IS Research Methods",
    " variational inference": "IS Research Methods",
    " VI": "IS Research Methods",
    " mean-field": "IS Research Methods",
    " full-rank": "IS Research Methods",
    " ADVI": "IS Research Methods",
    " Kucukelbir": "IS Research Methods",
    " automatic differentiation": "IS Research Methods",
    " normalizing flow": "IS Research Methods",
    " Rezende": "IS Research Methods",
    " Mohamed": "IS Research Methods",
    " planar flow": "IS Research Methods",
    " radial flow": "IS Research Methods",
    " inverse autoregressive": "IS Research Methods",
    " IAF": "IS Research Methods",
    " Kingma": "IS Research Methods",
    " Salimans": "IS Research Methods",
    " masked autoregressive": "IS Research Methods",
    " MAF": "IS Research Methods",
    " Papamakarios": "IS Research Methods",
    " neural autoregressive": "IS Research Methods",
    " NADE": "IS Research Methods",
    " Larochelle": "IS Research Methods",
    " Murray": "IS Research Methods",
    " MADE": "IS Research Methods",
    " Germain": "IS Research Methods",
    " Goodfellow": "IS Research Methods",
    " Bengio": "IS Research Methods",
    " Courville": "IS Research Methods",
    " deep learning": "IS Research Methods",
    " neural network": "IS Research Methods",
    " backpropagation": "IS Research Methods",
    " Rumelhart": "IS Research Methods",
    " Hinton": "IS Research Methods",
    " Williams": "IS Research Methods",
    " LeCun": "IS Research Methods",
    " Bottou": "IS Research Methods",
    " convolutional": "IS Research Methods",
    " CNN": "IS Research Methods",
    " LeNet": "IS Research Methods",
    " AlexNet": "IS Research Methods",
    " Krizhevsky": "IS Research Methods",
    " Sutskever": "IS Research Methods",
    " VGG": "IS Research Methods",
    " Simonyan": "IS Research Methods",
    " Zisserman": "IS Research Methods",
    " ResNet": "IS Research Methods",
    " He": "IS Research Methods",
    " Zhang": "IS Research Methods",
    " Ren": "IS Research Methods",
    " Sun": "IS Research Methods",
    " skip connection": "IS Research Methods",
    " batch normalization": "IS Research Methods",
    " Ioffe": "IS Research Methods",
    " Szegedy": "IS Research Methods",
    " Inception": "IS Research Methods",
    " GoogLeNet": "IS Research Methods",
    " DenseNet": "IS Research Methods",
    " Huang": "IS Research Methods",
    " Liu": "IS Research Methods",
    " Weinberger": "IS Research Methods",
    " EfficientNet": "IS Research Methods",
    " Tan": "IS Research Methods",
    " Le": "IS Research Methods",
    " compound scaling": "IS Research Methods",
    " NAS": "IS Research Methods",
    " neural architecture search": "IS Research Methods",
    " Zoph": "IS Research Methods",
    " Le": "IS Research Methods",
    " RL": "IS Research Methods",
    " reinforcement learning": "IS Research Methods",
    " Q-learning": "IS Research Methods",
    " Watkins": "IS Research Methods",
    " DQN": "IS Research Methods",
    " Mnih": "IS Research Methods",
    " Silver": "IS Research Methods",
    " policy gradient": "IS Research Methods",
    " REINFORCE": "IS Research Methods",
    " Williams": "IS Research Methods",
    " actor-critic": "IS Research Methods",
    " A2C": "IS Research Methods",
    " A3C": "IS Research Methods",
    " PPO": "IS Research Methods",
    " Schulman": "IS Research Methods",
    " Wolski": "IS Research Methods",
    " Dhariwal": "IS Research Methods",
    " TRPO": "IS Research Methods",
    " Schulman": "IS Research Methods",
    " Levine": "IS Research Methods",
    " Moritz": "IS Research Methods",
    " Jordan": "IS Research Methods",
    " Abbeel": "IS Research Methods",
    " SAC": "IS Research Methods",
    " Haarnoja": "IS Research Methods",
    " Zhou": "IS Research Methods",
    " Abbeel": "IS Research Methods",
    " Levine": "IS Research Methods",
    " TD3": "IS Research Methods",
    " Fujimoto": "IS Research Methods",
    " van Hoof": "IS Research Methods",
    " Meger": "IS Research Methods",
    " DDPG": "IS Research Methods",
    " Lillicrap": "IS Research Methods",
    " Hunt": "IS Research Methods",
    " Pritzel": "IS Research Methods",
    " Heess": "IS Research Methods",
    " Erez": "IS Research Methods",
    " Tassa": "IS Research Methods",
    " Silver": "IS Research Methods",
    " Wierstra": "IS Research Methods",
    " deterministic policy": "IS Research Methods",
    " gradient": "IS Research Methods",
    " D4PG": "IS Research Methods",
    " Barth-Maron": "IS Research Methods",
    " Hoffman": "IS Research Methods",
    " Budden": "IS Research Methods",
    " Firoiu": "IS Research Methods",
    " Meyer": "IS Research Methods",
    " Shahriari": "IS Research Methods",
    " Mankowitz": "IS Research Methods",
    " Pascanu": "IS Research Methods",
    " Sprechmann": "IS Research Methods",
    " Viola": "IS Research Methods",
    " Denil": "IS Research Methods",
    " de Freitas": "IS Research Methods",
    " distributed": "IS Research Methods",
    " IMPALA": "IS Research Methods",
    " Espeholt": "IS Research Methods",
    " Soyer": "IS Research Methods",
    " Munos": "IS Research Methods",
    " Simonyan": "IS Research Methods",
    " Mnih": "IS Research Methods",
    " Ward": "IS Research Methods",
    " Harley": "IS Research Methods",
    " Dunning": "IS Research Methods",
    " Legg": "IS Research Methods",
    " Hadsel": "IS Research Methods",
    " SEED": "IS Research Methods",
    " Kapturowski": "IS Research Methods",
    " Ober": "IS Research Methods",
    " Quan": "IS Research Methods",
    " Kapturowski": "IS Research Methods",
    " Dabney": "IS Research Methods",
    " Agapiou": "IS Research Methods",
    " Viola": "IS Research Methods",
    " Osindero": "IS Research Methods",
    " Valko": "IS Research Methods",
    " Badia": "IS Research Methods",
    " Puigdomenech": "IS Research Methods",
    " Vitvitskyi": "IS Research Methods",
    " Zhu": "IS Research Methods",
    " Kapturowski": "IS Research Methods",
    " Piot": "IS Research Methods",
    " Kapturowski": "IS Research Methods",
    " Sprechmann": "IS Research Methods",
    " Arulkumaran": "IS Research Methods",
    " Deisenroth": "IS Research Methods",
    " Brundage": "IS Research Methods",
    " Brennan": "IS Research Methods",
    " Smith": "IS Research Methods",
    " Wood": "IS Research Methods",
    " Packer": "IS Research Methods",
    " Abbeel": "IS Research Methods",
    " Amodei": "IS Research Methods",
    " Olah": "IS Research Methods",
    " Steinhardt": "IS Research Methods",
    " Christiano": "IS Research Methods",
    " Schulman": "IS Research Methods",
    " Manne": "IS Research Methods",
    " Trust and Safety": "IS Research Methods",
    " Alignment Forum": "IS Research Methods",
    " LessWrong": "IS Research Methods",
    " MIRI": "IS Research Methods",
    " OpenAI": "IS Research Methods",
    " Anthropic": "IS Research Methods",
    " DeepMind": "IS Research Methods",
    " Google Brain": "IS Research Methods",
    " FAIR": "IS Research Methods",
    " Meta AI": "IS Research Methods",
    " Microsoft Research": "IS Research Methods",
    " IBM Research": "IS Research Methods",
    " Allen Institute": "IS Research Methods",
    " Allen AI": "IS Research Methods",
    " AI2": "IS Research Methods",
    " Salesforce Research": "IS Research Methods",
    " NVIDIA Research": "IS Research Methods",
    " Huawei Noah's Ark": "IS Research Methods",
    " Baidu Research": "IS Research Methods",
    " Alibaba DAMO": "IS Research Methods",
    " Tencent AI Lab": "IS Research Methods",
    " ByteDance AI": "IS Research Methods",
    " SenseTime": "IS Research Methods",
    " Megvii": "IS Research Methods",
    " Yitu": "IS Research Methods",
    " CloudWalk": "IS Research Methods",
    " AIBrain": "IS Research Methods",
    " Preferred Networks": "IS Research Methods",
    " Preferred": "IS Research Methods",
    " DeNA": "IS Research Methods",
    " Cyberdyne": "IS Research Methods",
    " Neurala": "IS Research Methods",
    " Vicarious": "IS Research Methods",
    " Numenta": "IS Research Methods",
    " Cortical.io": "IS Research Methods",
    " Osaro": "IS Research Methods",
    " Kindred": "IS Research Methods",
    " Brain Corp": "IS Research Methods",
    " Embodied Intelligence": "IS Research Methods",
    " Covariant": "IS Research Methods",
    " Abbeel": "IS Research Methods",
    " Stein": "IS Research Methods",
    " Berkeley": "IS Research Methods",
    " OpenAI": "IS Research Methods",
    " Robotics": "IS Research Methods",
    " Rethink": "IS Research Methods",
    " Baxter": "IS Research Methods",
    " Sawyer": "IS Research Methods",
    " Universal Robots": "IS Research Methods",
    " UR": "IS Research Methods",
    " KUKA": "IS Research Methods",
    " ABB": "IS Research Methods",
    " Fanuc": "IS Research Methods",
    " Yaskawa": "IS Research Methods",
    " Motoman": "IS Research Methods",
    " Staubli": "IS Research Methods",
    " Denso": "IS Research Methods",
    " Epson": "IS Research Methods",
    " Omron": "IS Research Methods",
    " Mitsubishi": "IS Research Methods",
    " Panasonic": "IS Research Methods",
    " Siasun": "IS Research Methods",
    " Estun": "IS Research Methods",
    " Inovance": "IS Research Methods",
    " Topstar": "IS Research Methods",
    " Gogolook": "IS Research Methods",
    " Whoscall": "IS Research Methods",
    " AI startup": "IS Research Methods",
    " venture capital": "IS Research Methods",
    " Sequoia": "IS Research Methods",
    " A16Z": "IS Research Methods",
    " Andreessen Horowitz": "IS Research Methods",
    " Greylock": "IS Research Methods",
    " Bessemer": "IS Research Methods",
    " Lightspeed": "IS Research Methods",
    " Accel": "IS Research Methods",
    " Index": "IS Research Methods",
    " Benchmark": "IS Research Methods",
    " Founders Fund": "IS Research Methods",
    " Thiel": "IS Research Methods",
    " Khosla": "IS Research Methods",
    " Vinod": "IS Research Methods",
    " NEA": "IS Research Methods",
    " Kleiner Perkins": "IS Research Methods",
    " Caufield": "IS Research Methods",
    " Byers": "IS Research Methods",
    " Draper": "IS Research Methods",
    " Fisher": "IS Research Methods",
    " Jurvetson": "IS Research Methods",
    " DFJ": "IS Research Methods",
    " Tim Draper": "IS Research Methods",
    " Steve Jurvetson": "IS Research Methods",
    " Peter Thiel": "IS Research Methods",
    " Max Levchin": "IS Research Methods",
    " Luke Nosek": "IS Research Methods",
    " Ken Howery": "IS Research Methods",
    " Elon Musk": "IS Research Methods",
    " Reid Hoffman": "IS Research Methods",
    " Eric Schmidt": "IS Research Methods",
    " Diane Greene": "IS Research Methods",
    " Fei-Fei Li": "IS Research Methods",
    " Andrew Ng": "IS Research Methods",
    " Coursera": "IS Research Methods",
    " deeplearning.ai": "IS Research Methods",
    " Landing AI": "IS Research Methods",
    " WorkFusion": "IS Research Methods",
    " Max Yankelevich": "IS Research Methods",
    " Automation Anywhere": "IS Research Methods",
    " UiPath": "IS Research Methods",
    " Daniel Dines": "IS Research Methods",
    " Blue Prism": "IS Research Methods",
    " Alastair Bathgate": "IS Research Methods",
    " David Moss": "IS Research Methods",
    " Pegasystems": "IS Research Methods",
    " Alan Trefler": "IS Research Methods",
    " Appian": "IS Research Methods",
    " Matt Calkins": "IS Research Methods",
    " OutSystems": "IS Research Methods",
    " Paulo Rosado": "IS Research Methods",
    " Mendix": "IS Research Methods",
    " Derek Roos": "IS Research Methods",
    " Siemens": "IS Research Methods",
    " Mendix": "IS Research Methods",
    " Betty Blocks": "IS Research Methods",
    " Chris Obdam": "IS Research Methods",
    " Betty": "IS Research Methods",
    " Betty Blocks": "IS Research Methods",
    " WaveMaker": "IS Research Methods",
    " WaveMaker": "IS Research Methods",
    " ProntoForms": "IS Research Methods",
    " Pronto": "IS Research Methods",
    " Kianda": "IS Research Methods",
    " Derya": "IS Research Methods",
    " Soti": "IS Research Methods",
    " SOTI": "IS Research Methods",
    " Carl Rodrigues": "IS Research Methods",
    " MobileIron": "IS Research Methods",
    " Bob Tinker": "IS Research Methods",
    " Good": "IS Research Methods",
    " Good Technology": "IS Research Methods",
    " BlackBerry": "IS Research Methods",
    " BB": "IS Research Methods",
    " Chen": "IS Research Methods",
    " John Chen": "IS Research Methods",
    " Mike Lazaridis": "IS Research Methods",
    " Doug Fregin": "IS Research Methods",
    " RIM": "IS Research Methods",
    " Research In Motion": "IS Research Methods",
    " Nortel": "IS Research Methods",
    " BCE": "IS Research Methods",
    " Bell": "IS Research Methods",
    " AT&T": "IS Research Methods",
    " Verizon": "IS Research Methods",
    " T-Mobile": "IS Research Methods",
    " Sprint": "IS Research Methods",
    " US Cellular": "IS Research Methods",
    " Cricket": "IS Research Methods",
    " MetroPCS": "IS Research Methods",
    " Boost Mobile": "IS Research Methods",
    " Virgin Mobile": "IS Research Methods",
    " TracFone": "IS Research Methods",
    " Straight Talk": "IS Research Methods",
    " Net10": "IS Research Methods",
    " Total Wireless": "IS Research Methods",
    " Simple Mobile": "IS Research Methods",
    " Walmart Family": "IS Research Methods",
    " GoSmart": "IS Research Methods",
    " Telcel America": "IS Research Methods",
    " SafeLink": "IS Research Methods",
    " Assurance": "IS Research Methods",
    " Q Link": "IS Research Methods",
    " StandUp": "IS Research Methods",
    " StandUp Wireless": "IS Research Methods",
    " TerraCom": "IS Research Methods",
    " YourTel": "IS Research Methods",
    " Tag Mobile": "IS Research Methods",
    " FeelSafe": "IS Research Methods",
    " Life Wireless": "IS Research Methods",
    " Assist": "IS Research Methods",
    " Assist Wireless": "IS Research Methods",
    " TruConnect": "IS Research Methods",
    " enTouch": "IS Research Methods",
    " Boomerang": "IS Research Methods",
    " Cintex": "IS Research Methods",
    " NewPhone": "IS Research Methods",
    " AirTalk": "IS Research Methods",
    " Tempo": "IS Research Methods",
    " Tempo Wireless": "IS Research Methods",
    " Access": "IS Research Methods",
    " Access Wireless": "IS Research Methods",
    " American Assistance": "IS Research Methods",
    " American Broadband": "IS Research Methods",
    " American Wireless": "IS Research Methods",
    " Blue Jay": "IS Research Methods",
    " Blue Jay Wireless": "IS Research Methods",
    " Charity": "IS Research Methods",
    " Charity Mobile": "IS Research Methods",
    " Cleartalk": "IS Research Methods",
    " Clear Talk": "IS Research Methods",
    " Copper Valley": "IS Research Methods",
    " Digital Phone": "IS Research Methods",
    " Easy Wireless": "IS Research Methods",
    " Exalt": "IS Research Methods",
    " Exalt Wireless": "IS Research Methods",
    " Global Connection": "IS Research Methods",
    " Global Connection Inc": "IS Research Methods",
    " GCI": "IS Research Methods",
    " GCI Wireless": "IS Research Methods",
    " Hello Mobile": "IS Research Methods",
    " I-Wireless": "IS Research Methods",
    " I Wireless": "IS Research Methods",
    " Infinity": "IS Research Methods",
    " Infinity Mobile": "IS Research Methods",
    " Inland": "IS Research Methods",
    " Inland Cellular": "IS Research Methods",
    " Kajeet": "IS Research Methods",
    " Liberty": "IS Research Methods",
    " Liberty Wireless": "IS Research Methods",
    " Mobi": "IS Research Methods",
    " Mobi Wireless": "IS Research Methods",
    " Nexus": "IS Research Methods",
    " Nexus Wireless": "IS Research Methods",
    " North American": "IS Research Methods",
    " North American Cellular": "IS Research Methods",
    " Optimum": "IS Research Methods",
    " Optimum Mobile": "IS Research Methods",
    " PTel": "IS Research Methods",
    " PTel Mobile": "IS Research Methods",
    " Puerto Rico": "IS Research Methods",
    " Puerto Rico Telephone": "IS Research Methods",
    " Sage": "IS Research Methods",
    " Sage Telecom": "IS Research Methods",
    " Seawolf": "IS Research Methods",
    " Seawolf Wireless": "IS Research Methods",
    " Southern Linc": "IS Research Methods",
    " Standing Rock": "IS Research Methods",
    " Standing Rock Telecom": "IS Research Methods",
    " Swift": "IS Research Methods",
    " Swift Wireless": "IS Research Methods",
    " Syringa": "IS Research Methods",
    " Syringa Wireless": "IS Research Methods",
    " T2": "IS Research Methods",
    " T2 Wireless": "IS Research Methods",
    " Tag": "IS Research Methods",
    " Telemetrix": "IS Research Methods",
    " Telemetrix Inc": "IS Research Methods",
    " Tempo": "IS Research Methods",
    " Terracom": "IS Research Methods",
    " Total Call": "IS Research Methods",
    " Total Call Mobile": "IS Research Methods",
    " Tribal": "IS Research Methods",
    " Tribal Wireless": "IS Research Methods",
    " Union": "IS Research Methods",
    " Union Wireless": "IS Research Methods",
    " United": "IS Research Methods",
    " United Wireless": "IS Research Methods",
    " UScellular": "IS Research Methods",
    " US Cellular": "IS Research Methods",
    " Viaero": "IS Research Methods",
    " Viaero Wireless": "IS Research Methods",
    " West Central": "IS Research Methods",
    " West Central Wireless": "IS Research Methods",
    " Wireless for Hope": "IS Research Methods",
    " Wraase": "IS Research Methods",
    " Yourtel": "IS Research Methods",
    " ZingPCS": "IS Research Methods",
    " 5G": "IS Research Methods",
    " 4G": "IS Research Methods",
    " LTE": "IS Research Methods",
    " VoLTE": "IS Research Methods",
    " VoIP": "IS Research Methods",
    " SIP": "IS Research Methods",
    " IMS": "IS Research Methods",
    " RCS": "IS Research Methods",
    " eSIM": "IS Research Methods",
    " iSIM": "IS Research Methods",
    " soft SIM": "IS Research Methods",
    " embedded SIM": "IS Research Methods",
    " M2M": "IS Research Methods",
    " IoT": "IS Research Methods",
    " NB-IoT": "IS Research Methods",
    " LTE-M": "IS Research Methods",
    " LoRa": "IS Research Methods",
    " LoRaWAN": "IS Research Methods",
    " Sigfox": "IS Research Methods",
    " Ingenu": "IS Research Methods",
    " RPMA": "IS Research Methods",
    " Weightless": "IS Research Methods",
    " Weightless-P": "IS Research Methods",
    " Weightless-N": "IS Research Methods",
    " Weightless-W": "IS Research Methods",
    " Symphony Link": "IS Research Methods",
    " Haystack": "IS Research Methods",
    " DASH7": "IS Research Methods",
    " Mode C": "IS Research Methods",
    " IEEE 802.15.4": "IS Research Methods",
    " Zigbee": "IS Research Methods",
    " Z-Wave": "IS Research Methods",
    " Thread": "IS Research Methods",
    " Matter": "IS Research Methods",
    " Bluetooth": "IS Research Methods",
    " BLE": "IS Research Methods",
    " Bluetooth Low Energy": "IS Research Methods",
    " UWB": "IS Research Methods",
    " Ultra Wideband": "IS Research Methods",
    " NFC": "IS Research Methods",
    " RFID": "IS Research Methods",
    " QR": "IS Research Methods",
    " barcode": "IS Research Methods",
    " barcode scanner": "IS Research Methods",
    " POS": "IS Research Methods",
    " point of sale": "IS Research Methods",
    " payment terminal": "IS Research Methods",
    " credit card reader": "IS Research Methods",
    " magstripe": "IS Research Methods",
    " EMV": "IS Research Methods",
    " chip and PIN": "IS Research Methods",
    " contactless": "IS Research Methods",
    " tap to pay": "IS Research Methods",
    " Apple Pay": "IS Research Methods",
    " Google Pay": "IS Research Methods",
    " Samsung Pay": "IS Research Methods",
    " PayPal": "IS Research Methods",
    " Venmo": "IS Research Methods",
    " Cash App": "IS Research Methods",
    " Zelle": "IS Research Methods",
    " Square": "IS Research Methods",
    " Block": "IS Research Methods",
    " Stripe": "IS Research Methods",
    " Collison": "IS Research Methods",
    " Patrick Collison": "IS Research Methods",
    " John Collison": "IS Research Methods",
    " Adyen": "IS Research Methods",
    " Shopify": "IS Research Methods",
    " Tobias Lutke": "IS Research Methods",
    " Klarna": "IS Research Methods",
    " Sebastian Siemiatkowski": "IS Research Methods",
    " Niklas Adalberth": "IS Research Methods",
    " Victor Jacobsson": "IS Research Methods",
    " Affirm": "IS Research Methods",
    " Max Levchin": "IS Research Methods",
    " Afterpay": "IS Research Methods",
    " Nick Molnar": "IS Research Methods",
    " Anthony Eisen": "IS Research Methods",
    " QuadPay": "IS Research Methods",
    " Brad Lindenberg": "IS Research Methods",
    " Adam Ezra": "IS Research Methods",
    " Sezzle": "IS Research Methods",
    " Charlie Youakim": "IS Research Methods",
    " Splitit": "IS Research Methods",
    " Gil Don": "IS Research Methods",
    " Alon Feit": "IS Research Methods",
    " Zip Co": "IS Research Methods",
    " Larry Diamond": "IS Research Methods",
    " Peter Gray": "IS Research Methods",
    " Laybuy": "IS Research Methods",
    " Gary Rohloff": "IS Research Methods",
    " OpenPay": "IS Research Methods",
    " Michael Eidel": "IS Research Methods",
    " Richard Wormald": "IS Research Methods",
    " humm": "IS Research Methods",
    " Chris Lamers": "IS Research Methods",
    " Flexigroup": "IS Research Methods",
    " Bundll": "IS Research Methods",
    " Little Birdie": "IS Research Methods",
    " Latitude": "IS Research Methods",
    " LatitudePay": "IS Research Methods",
    " Latitude Financial": "IS Research Methods",
    " Ahmed Fahour": "IS Research Methods",
    " Mastercard": "IS Research Methods",
    " Visa": "IS Research Methods",
    " American Express": "IS Research Methods",
    " Discover": "IS Research Methods",
    " Diners Club": "IS Research Methods",
    " JCB": "IS Research Methods",
    " UnionPay": "IS Research Methods",
    " RuPay": "IS Research Methods",
    " MIR": "IS Research Methods",
    " Girocard": "IS Research Methods",
    " Bancontact": "IS Research Methods",
    " iDEAL": "IS Research Methods",
    " SOFORT": "IS Research Methods",
    " Giropay": "IS Research Methods",
    " ELV": "IS Research Methods",
    " SEPA": "IS Research Methods",
    " SEPA direct debit": "IS Research Methods",
    " SEPA credit transfer": "IS Research Methods",
    " instant SEPA": "IS Research Methods",
    " TARGET2": "IS Research Methods",
    " TARGET Instant Payment": "IS Research Methods",
    " TIPS": "IS Research Methods",
    " RT1": "IS Research Methods",
    " EBA CLEARING": "IS Research Methods",
    " STEP2": "IS Research Methods",
    " CORE": "IS Research Methods",
    " B2B": "IS Research Methods",
    " STEP1": "IS Research Methods",
    " EURO1": "IS Research Methods",
    " ERPF": "IS Research Methods",
    " CSM": "IS Research Methods",
    " EPC": "IS Research Methods",
    " European Payments Council": "IS Research Methods",
    " EPC QR": "IS Research Methods",
    " EPC Payment"