THEORY_MODEL_ROLES = {
    1: {
        "form": "Causal path model",
        "inputs": ("External variables",),
        "mechanisms": ("Perceived ease of use", "Perceived usefulness", "Attitude", "Behavioral intention"),
        "outcomes": ("Actual use",),
    },
    2: {
        "form": "Causal extension",
        "inputs": ("Subjective norm", "Image", "Job relevance", "Output quality", "Result demonstrability", "Perceived ease of use"),
        "mechanisms": ("Perceived usefulness", "Behavioral intention"),
        "outcomes": ("Use",),
        "moderators": ("Experience", "Voluntariness"),
    },
    3: {
        "form": "Causal extension",
        "inputs": ("Anchors", "Adjustments", "TAM2 determinants"),
        "mechanisms": ("Perceived ease of use", "Perceived usefulness", "Behavioral intention"),
        "outcomes": ("Use",),
    },
    4: {
        "form": "Causal path model",
        "inputs": ("Performance expectancy", "Effort expectancy", "Social influence", "Facilitating conditions"),
        "mechanisms": ("Behavioral intention",),
        "outcomes": ("Use behavior",),
        "moderators": ("Gender", "Age", "Experience", "Voluntariness of use"),
    },
    5: {
        "form": "Consumer adoption model",
        "inputs": ("Performance expectancy", "Effort expectancy", "Social influence", "Hedonic motivation", "Price value", "Habit", "Facilitating conditions"),
        "mechanisms": ("Behavioral intention",),
        "outcomes": ("Use behavior",),
        "moderators": ("Age", "Gender", "Experience"),
    },
    6: {
        "form": "Causal path model",
        "inputs": ("Behavioral beliefs", "Normative beliefs"),
        "mechanisms": ("Attitude toward behavior", "Subjective norm", "Behavioral intention"),
        "outcomes": ("Behavior",),
    },
    7: {
        "form": "Causal path model",
        "inputs": ("Attitude", "Subjective norm", "Perceived behavioral control"),
        "mechanisms": ("Behavioral intention",),
        "outcomes": ("Behavior",),
    },
    8: {
        "form": "Diffusion process",
        "inputs": ("Relative advantage", "Compatibility", "Complexity", "Trialability", "Observability", "Communication channels", "Time", "Social system"),
        "mechanisms": ("Knowledge", "Persuasion", "Decision", "Implementation"),
        "outcomes": ("Confirmation", "Adoption and diffusion over time"),
    },
    9: {
        "form": "Continuance model",
        "inputs": ("Confirmation",),
        "mechanisms": ("Perceived usefulness", "Satisfaction"),
        "outcomes": ("Continuance intention",),
    },
    10: {
        "form": "Success model",
        "inputs": ("System quality", "Information quality", "Service quality"),
        "mechanisms": ("Use or intention to use", "User satisfaction"),
        "outcomes": ("Net benefits",),
    },
    11: {
        "form": "Fit model",
        "inputs": ("Task characteristics", "Technology characteristics"),
        "mechanisms": ("Task-technology fit", "Utilization"),
        "outcomes": ("Performance impact",),
    },
    12: {
        "form": "Cognitive fit model",
        "inputs": ("Problem representation", "Task type"),
        "mechanisms": ("Cognitive fit", "Lower mental transformation"),
        "outcomes": ("Problem-solving performance",),
    },
    13: {
        "form": "Media-choice contingency model",
        "inputs": ("Task equivocality", "Media richness characteristics"),
        "mechanisms": ("Media choice and fit"),
        "outcomes": ("Richer or leaner media choice",),
    },
    14: {
        "form": "Fit and information-processing model",
        "inputs": ("Uncertainty or equivocality", "Organizational design", "IS capability"),
        "mechanisms": ("Information requirements", "Information processing capacity", "Fit"),
        "outcomes": ("Performance and coordination quality",),
    },
    15: {
        "form": "Strategic resource model",
        "inputs": ("Resources", "Capabilities"),
        "mechanisms": ("VRIN attributes", "Sustained competitive advantage"),
        "outcomes": ("Performance",),
    },
    16: {
        "form": "Capability renewal cycle",
        "inputs": ("Sensing", "Seizing"),
        "mechanisms": ("Transforming or reconfiguring"),
        "outcomes": ("Renewed resource base", "Advantage"),
    },
    17: {
        "form": "Value creation path",
        "inputs": ("IT resources", "Complementary organizational resources"),
        "mechanisms": ("Business process performance"),
        "outcomes": ("Organizational performance",),
    },
    18: {
        "form": "Alignment framework, not a single IV to DV chain",
        "inputs": ("Business strategy", "IT strategy", "Business infrastructure", "IT infrastructure"),
        "mechanisms": ("Strategic fit", "Functional integration"),
        "outcomes": ("Alignment quality",),
    },
    19: {
        "form": "Adoption framework",
        "inputs": ("Technology context", "Organization context", "Environment context"),
        "mechanisms": ("Adoption or assimilation decision"),
        "outcomes": ("Adoption or assimilation",),
    },
    20: {
        "form": "Contingency model",
        "inputs": ("Contingency factors",),
        "mechanisms": ("Best-fitting structure or design"),
        "outcomes": ("Performance",),
    },
    21: {
        "form": "Executive cognition model",
        "inputs": ("Top managers' experiences", "Values", "Cognition"),
        "mechanisms": ("Strategic choices"),
        "outcomes": ("Organizational outcomes",),
    },
    22: {
        "form": "Governance choice model",
        "inputs": ("Asset specificity", "Uncertainty", "Frequency"),
        "mechanisms": ("Transaction costs"),
        "outcomes": ("Governance choice",),
    },
    23: {
        "form": "Governance and monitoring model",
        "inputs": ("Information asymmetry", "Goal conflict"),
        "mechanisms": ("Agency problems", "Monitoring and incentives"),
        "outcomes": ("Lower agency loss",),
        "moderators": ("Principal-agent relationship context",),
    },
    24: {
        "form": "Uncertainty-reduction model",
        "inputs": ("Hidden quality", "Costly credible signal"),
        "mechanisms": ("Signal interpretation"),
        "outcomes": ("Receiver quality judgment", "Reduced uncertainty"),
    },
    25: {
        "form": "Reinforcing loop",
        "inputs": ("Installed base", "Users", "Complementors"),
        "mechanisms": ("User value", "Adoption growth"),
        "outcomes": ("Larger installed base", "More value"),
    },
    26: {
        "form": "Platform ecosystem model",
        "inputs": ("Platform core", "Boundary resources", "Governance rules"),
        "mechanisms": ("Complementor participation", "Complementary innovation"),
        "outcomes": ("User value", "Ecosystem growth"),
    },
    27: {
        "form": "Co-creation logic, not a simple IV to DV chain",
        "inputs": ("Provider operant resources", "Customer operant resources"),
        "mechanisms": ("Value co-creation in use"),
        "outcomes": ("Value in context",),
    },
    28: {
        "form": "Exchange evaluation model",
        "inputs": ("Perceived rewards", "Perceived costs", "Reciprocity", "Trust"),
        "mechanisms": ("Exchange evaluation"),
        "outcomes": ("Contribution", "Continued relationship"),
    },
    29: {
        "form": "Reciprocal joint-optimization model",
        "inputs": ("Technical system", "Social system"),
        "mechanisms": ("Joint optimization"),
        "outcomes": ("Work system performance",),
    },
    30: {
        "form": "Recursive structure model, not a one-way IV to DV chain",
        "inputs": ("Rules", "Resources", "Human action"),
        "mechanisms": ("Reproduction or change of structure"),
        "outcomes": ("Updated structure",),
    },
    31: {
        "form": "Appropriation model",
        "inputs": ("Technology structures", "Spirit"),
        "mechanisms": ("Group appropriation"),
        "outcomes": ("Interaction process", "Group outcomes"),
    },
    32: {
        "form": "Institutional pressure model",
        "inputs": ("Coercive pressure", "Mimetic pressure", "Normative pressure"),
        "mechanisms": ("Legitimacy seeking", "Isomorphism"),
        "outcomes": ("Adoption",),
    },
    33: {
        "form": "Network-building process",
        "inputs": ("Human actants", "Nonhuman actants"),
        "mechanisms": ("Translation", "Enrollment", "Network alignment"),
        "outcomes": ("Stabilization", "Black box"),
    },
    34: {
        "form": "Affordance actualization model",
        "inputs": ("Artifact features", "User goals and capabilities", "Context"),
        "mechanisms": ("Affordances", "Affordance actualization"),
        "outcomes": ("Outcomes",),
    },
    35: {
        "form": "Boundary spanning framework, not a single IV to DV chain",
        "inputs": ("Community A", "Boundary object", "Community B"),
        "mechanisms": ("Interpretive flexibility", "Shared structure for coordination"),
        "outcomes": ("Coordination across communities",),
    },
    36: {
        "form": "Practice-based sociomaterial model",
        "inputs": ("Human action", "Material arrangement"),
        "mechanisms": ("Practice enactment"),
        "outcomes": ("Situated practice outcomes",),
    },
    37: {
        "form": "Change sequence model",
        "inputs": ("Equilibrium",),
        "mechanisms": ("Punctuation", "Revolutionary change"),
        "outcomes": ("New equilibrium",),
    },
    38: {
        "form": "Reciprocal triadic model",
        "inputs": ("Environment", "Person or cognition", "Behavior"),
        "mechanisms": ("Reciprocal determinism", "Self-efficacy"),
        "outcomes": ("Adaptive behavior",),
    },
    39: {
        "form": "Motivation model",
        "inputs": ("Autonomy", "Competence", "Relatedness"),
        "mechanisms": ("Intrinsic motivation"),
        "outcomes": ("Engagement", "Persistence"),
    },
    40: {
        "form": "Experience model",
        "inputs": ("Challenge-skill balance", "Focused attention"),
        "mechanisms": ("Flow"),
        "outcomes": ("Enjoyment", "Deep engagement"),
    },
    41: {
        "form": "Need-gratification model",
        "inputs": ("Needs", "Gratifications sought"),
        "mechanisms": ("Media or platform choice"),
        "outcomes": ("Gratifications obtained",),
    },
    42: {
        "form": "Dual-route persuasion model",
        "inputs": ("Motivation", "Ability", "Argument quality", "Peripheral cues"),
        "mechanisms": ("Central route", "Peripheral route"),
        "outcomes": ("Attitude change",),
    },
    43: {
        "form": "Sensemaking process",
        "inputs": ("Ecological change", "Surprise"),
        "mechanisms": ("Enactment", "Selection"),
        "outcomes": ("Retention", "Plausible action"),
    },
    44: {
        "form": "Behavioral decision model",
        "inputs": ("Reference point",),
        "mechanisms": ("Gain or loss framing", "Loss aversion", "Value function"),
        "outcomes": ("Choice",),
    },
    45: {
        "form": "Protection path model",
        "inputs": ("Severity", "Vulnerability", "Response efficacy", "Self-efficacy", "Response cost"),
        "mechanisms": ("Threat appraisal", "Coping appraisal", "Protection motivation"),
        "outcomes": ("Protective behavior",),
    },
    46: {
        "form": "Deterrence model",
        "inputs": ("Sanction certainty", "Sanction severity", "Celerity"),
        "mechanisms": ("Deterrence"),
        "outcomes": ("Lower misconduct",),
    },
    47: {
        "form": "Stress and coping process",
        "inputs": ("IT event or stressor",),
        "mechanisms": ("Primary appraisal", "Secondary appraisal", "Problem-focused or emotion-focused coping"),
        "outcomes": ("Adaptation outcome",),
    },
    48: {
        "form": "Disclosure tradeoff model",
        "inputs": ("Perceived benefits", "Perceived privacy risk"),
        "mechanisms": ("Privacy calculus"),
        "outcomes": ("Disclosure intention", "Disclosure behavior"),
    },
    49: {
        "form": "Trust formation model",
        "inputs": ("Ability", "Benevolence", "Integrity", "Structural assurance"),
        "mechanisms": ("Trusting beliefs", "Trusting intention"),
        "outcomes": ("Reliance", "Willingness to be vulnerable"),
    },
    50: {
        "form": "Presence and relational outcome model",
        "inputs": ("Medium cues", "Immediacy", "Intimacy"),
        "mechanisms": ("Perceived social presence"),
        "outcomes": ("Warmth", "Trust", "Engagement"),
    },
}
